#! /bin/sh
VERSION=$(git describe --abbrev=0 --tags)
echo "Current Version:" $VERSION
cat >./VERSION <<EOF
$VERSION
EOF
cat >./engine/version.go <<EOF
//
// Warning:
// This file is generated by go compiler, don't change it!!!
//
package engine

type ver struct {
	Version   string
	ReleaseTime string
}

var defaultVer = ver{
	Version:   \`$VERSION\`,
	ReleaseTime: "$(echo $(date "+%Y-%m-%d %H:%M:%S"))",
}
EOF
echo "Generate Version Susseccfully"
