#! /bin/sh
VERSION="$(git describe --tags $(git rev-list --tags --max-count=1))-$(git rev-list --tags --max-count=1)"
echo "Current Version:" ${VERSION}
cat >./VERSION <<EOF
$VERSION
EOF
cat >./engine/version.go <<EOF
//
// Warning:
// This file is generated by go compiler, don't change it!!!
//
package engine

type ver struct {
	Version   string
	ReleaseTime string
}

var defaultVer = ver{
	Version:   \`$VERSION\`,
	ReleaseTime: "$(echo $(date "+%Y-%m-%d %H:%M:%S"))",
}
EOF
echo "Generate Version Susseccfully"
