#! /bin/bash
VERSION="$(git describe --tags $(git rev-list --tags --max-count=1))"
HASH=$(git rev-list --tags --max-count=1)

#######################################################################
## Gen Version
#######################################################################
cat >./typex/version.go <<EOF
// Warning:
//
//	This file is generated by go compiler, don't change it!!!
package typex

type Version struct {
	Version     string
	ReleaseTime string
	Arch        string
	Dist        string
}

var DefaultVersion = Version{
	Version:   \`${VERSION}\`,
	ReleaseTime: "$(echo $(date "+%Y-%m-%d %H:%M:%S"))",
}
var Banner = \`
 **  Welcome to RULEX framework world <'_'>
**   Version: ${VERSION}-${HASH:0:15}
 **  Document: https://hootrhino.github.io
\`
EOF

echo "Generate Version Susseccfully"

