{
 "title": "Go Metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(go_goroutines, job)"
   },
   {
    "name": "project",
    "query": "label_values(go_goroutines{job=\"$job\"}, project)"
   },
   {
    "name": "env",
    "query": "label_values(go_goroutines{job=\"$job\", project=\"$project\"}, env_name)"
   },
   {
    "name": "stage",
    "query": "label_values(go_goroutines{job=\"$job\", project=\"$project\", env_name=\"$env\"}, stage)"
   },
   {
    "name": "service",
    "query": "label_values(go_goroutines{job=\"$job\", project=\"$project\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "process cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(goruntime_process_cpu_seconds_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}[2m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_heap_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_heap_idle_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_heap_released_bytes-{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_gc_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"} - go_memstats_other_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_next_gc_bytes-{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_stack_sys_bytes-{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}[2m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"} - go_memstats_frees_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}[2m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}[2m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  }
 ]
}