//
// Warning:
// This file is generated by go compiler, don't change it!!!
//
package engine

type ver struct {
	Version   string
	ReleaseTime string
}

var defaultVer = ver{
	Version:   `0.0.1-preview`,
	ReleaseTime: "2021-09-24 10:39:08",
}
