//
// Warning:
// This file is generated by go compiler, don't change it!!!
//
package engine

type ver struct {
	Version   string
	ReleaseTime string
}

var defaultVer = ver{
	Version:   `0.0.1-preview-232add3b533016cfda4b8bac177a2629cb37d5c9`,
	ReleaseTime: "2021-09-25 16:36:24",
}
