package cron_task

// CRON_TASK_TYPE
const (
	CRON_TASK_TYPE_LINUX_SHELL = "LINUX_SHELL"
)

const PERM_0777 = 0777

// CRON_RESULT_STATUS
const (
	CRON_RESULT_STATUS_RUNNING = "RUNNING"
	CRON_RESULT_STATUS_END     = "END"
)
