// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: xcodec.proto

package rulexrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CodecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CodecRequest) Reset() {
	*x = CodecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xcodec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodecRequest) ProtoMessage() {}

func (x *CodecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xcodec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodecRequest.ProtoReflect.Descriptor instead.
func (*CodecRequest) Descriptor() ([]byte, []int) {
	return file_xcodec_proto_rawDescGZIP(), []int{0}
}

func (x *CodecRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CodecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CodecResponse) Reset() {
	*x = CodecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xcodec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodecResponse) ProtoMessage() {}

func (x *CodecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xcodec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodecResponse.ProtoReflect.Descriptor instead.
func (*CodecResponse) Descriptor() ([]byte, []int) {
	return file_xcodec_proto_rawDescGZIP(), []int{1}
}

func (x *CodecResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CodecResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CodecResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_xcodec_proto protoreflect.FileDescriptor

var file_xcodec_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x78, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x72, 0x75, 0x6c, 0x65, 0x78, 0x72, 0x70, 0x63, 0x22, 0x24, 0x0a, 0x0c, 0x43, 0x6f, 0x64, 0x65,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x51,
	0x0a, 0x0d, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x81, 0x01, 0x0a, 0x05, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x3b, 0x0a, 0x06, 0x44,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x78, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x72, 0x75, 0x6c, 0x65, 0x78, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x78, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x75, 0x6c,
	0x65, 0x78, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x0a, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x78, 0x72, 0x70,
	0x63, 0x42, 0x07, 0x58, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x00, 0x5a, 0x0b, 0x2e, 0x2f,
	0x3b, 0x72, 0x75, 0x6c, 0x65, 0x78, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_xcodec_proto_rawDescOnce sync.Once
	file_xcodec_proto_rawDescData = file_xcodec_proto_rawDesc
)

func file_xcodec_proto_rawDescGZIP() []byte {
	file_xcodec_proto_rawDescOnce.Do(func() {
		file_xcodec_proto_rawDescData = protoimpl.X.CompressGZIP(file_xcodec_proto_rawDescData)
	})
	return file_xcodec_proto_rawDescData
}

var file_xcodec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xcodec_proto_goTypes = []interface{}{
	(*CodecRequest)(nil),  // 0: rulexrpc.CodecRequest
	(*CodecResponse)(nil), // 1: rulexrpc.CodecResponse
}
var file_xcodec_proto_depIdxs = []int32{
	0, // 0: rulexrpc.Codec.Decode:input_type -> rulexrpc.CodecRequest
	0, // 1: rulexrpc.Codec.Encode:input_type -> rulexrpc.CodecRequest
	1, // 2: rulexrpc.Codec.Decode:output_type -> rulexrpc.CodecResponse
	1, // 3: rulexrpc.Codec.Encode:output_type -> rulexrpc.CodecResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xcodec_proto_init() }
func file_xcodec_proto_init() {
	if File_xcodec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xcodec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xcodec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xcodec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xcodec_proto_goTypes,
		DependencyIndexes: file_xcodec_proto_depIdxs,
		MessageInfos:      file_xcodec_proto_msgTypes,
	}.Build()
	File_xcodec_proto = out.File
	file_xcodec_proto_rawDesc = nil
	file_xcodec_proto_goTypes = nil
	file_xcodec_proto_depIdxs = nil
}
