//
// Warning:
//   This file is generated by go compiler, don't change it!!!
//   Generated Time: "2022-08-16 23:55:26"
//   Build on: Linux wwhai 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
//
package typex

type Version struct {
	Version   string
	ReleaseTime string
}

var DefaultVersion = Version{
	Version:   `V0.3.2`,
	ReleaseTime: "2022-08-16 23:55:26",
}

