//
// Warning:
//   This file is generated by go compiler, don't change it!!!
//   Generated Time: "2023-02-27 13:52:59"
//   Build on: 5.19.0-32-generic
//
package typex

type Version struct {
	Version   string
	ReleaseTime string
}

var DefaultVersion = Version{
	Version:   `V0.4.2`,
	ReleaseTime: "2023-02-27 13:52:59",
}

