// Warning:
//
//	This file is generated by go compiler, don't change it!!!
package typex

var MainVersion string

type VersionInfo struct {
	ReleaseTime string
	Arch        string
	Product     string
	Dist        string
}

var DefaultVersionInfo = VersionInfo{
	Product:        "COMMON",
	ReleaseTime: "2024-01-04 21:15:55",
}
var Banner = `
 **  Welcome to RULEX framework world <'_'>
**   Version: v0.6.5-f65434ec644585e
 **  Document: https://hootrhino.github.io
`
