name: 4- Arm32-V7 构建测试

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Go build
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        run: |
          sudo apt update -y
          sudo apt install jq protobuf-compiler gcc-arm-linux-gnueabi -y
          chmod 755 ./gen_info.sh
          chmod +x ./gen_info.sh
          chmod 755 ./gen_proto.sh
          chmod +x ./gen_proto.sh
          make
          CGO_ENABLED=1 GOARM=7 GOOS=linux GOARCH=arm CC=arm-linux-gnueabi-gcc go build -ldflags "-s -w -linkmode external -extldflags -static" main.go
