FROM golang:latest

ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct 

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
      build-essential \
      git \
      zip \
      make \
      gcc-arm-linux-gnueabi \
      bzip2 \
      wget && \
    apt-get clean

WORKDIR /APP
RUN git clone https://gitee.com/wwhai/rulex.git
RUN cd rulex &&  CC=arm-linux-gnueabi-gcc GOARM=7 GOARCH=arm GOOS=linux CGO_ENABLED=1 go build  -v -o arm32 main.go

ENTRYPOINT [ "/bin/bash" ]