FROM arm32v7/alpine
LABEL author="wwhai"
LABEL email="cnwwhai@gmail.com"
LABEL homepage="rulex.ezlinker.cn"
ENV APP_NAME="rulex"
ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOPROXY="https://goproxy.cn,direct"
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
            && apk add make build-base go


ADD . /APP_NAME/
# RUN cd /APP_NAME/ && make xx

ENTRYPOINT ["/bin/bash"]
