FROM arm32v7/alpine
LABEL author="wwhai"
LABEL email="cnwwhai@gmail.com"
LABEL homepage="rulex.ezlinker.cn"
ENV APP_NAME="rulex"
ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOPROXY="https://goproxy.cn,direct"

RUN apk add make build-base go git zip
WORKDIR /APP
RUN git clone https://gitee.com/wwhai/rulex.git
RUN cd rulex && go build -o rulex main.go
RUN zip –q –r rulex.zip ./*
ENTRYPOINT [ "/bin/bash" ]